sudo: false
language: node_js
node_js:
  - 'stable'
  - '8'
  - '7'
  - '6'
script:
  - npm test
  - npm run report
after_script:
  - ls -lh docs/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    node: stable
    branch: master
  local_dir: docs
